name: FacileJdbc Build

on:
    push:
        branches:
            - main
            - releases/*
            - issues/*
    pull_request:
        branches:
            - main
            - releases/*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Build with Gradle
              run: ./gradlew build
